# Generated by Django 4.2.6 on 2023-10-22 16:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='permisos',
            fields=[
            ],
            options={
                'verbose_name': 'Custom Permission Name',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(),
        ),
    ]
