# Generated by Django 4.2.6 on 2023-10-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_permisos_alter_comunicado_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='permisos',
        ),
    ]
