# Generated by Django 4.2.6 on 2023-10-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
